# Generated by Django 4.2.21 on 2025-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0006_alter_course_id_alter_question_id_alter_result_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.TextField(max_length=600),
        ),
    ]
