# Generated by Django 4.2.21 on 2025-05-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0010_remove_result_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="marks",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
