# Generated by Django 5.2.1 on 2025-05-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0011_alter_question_marks"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
