# Generated by Django 5.2.2 on 2025-06-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0016_alter_course_options_alter_result_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cource_question_image",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="exam.course",
            ),
        ),
    ]
