# Generated by Django 5.2.2 on 2025-06-06 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0017_alter_cource_question_image_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cource_question_image",
            name="created_at",
        ),
    ]
