# Generated by Django 5.2.2 on 2025-06-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0018_remove_cource_question_image_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Kurs",
                "verbose_name_plural": "Kurslar",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Test savollarini yuklang (agar matn shaklida bo'lmasa)",
                null=True,
                upload_to="courses/questions/",
                verbose_name="Savollar rasmi",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(
                help_text="Kursning to'liq nomi",
                max_length=100,
                verbose_name="Kurs nomi",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=None, verbose_name="Yaratilgan sana"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="question_number",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maksimal test savollari soni",
                verbose_name="Savollar soni",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="total_marks",
            field=models.PositiveIntegerField(
                default=100, help_text="Testning umumiy balli", verbose_name="Jami ball"
            ),
        ),
        migrations.DeleteModel(
            name="Cource_Question_Image",
        ),
    ]
