# Generated by Django 5.2.2 on 2025-06-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0019_alter_course_options_course_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="text_content",
            field=models.TextField(
                blank=True,
                help_text="Savol generatsiya qilish uchun to'g'ridan-to'g'ri matn",
                null=True,
                verbose_name="Matnli kontent",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Test savollari generatsiya qilish uchun rasm (Agar matn shaklida bo'lmasa)",
                null=True,
                upload_to="courses/questions/",
                verbose_name="Savollar uchun rasm",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="question_number",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maksimal test savollari soni (5-100 oralig'ida)",
                verbose_name="Savollar soni",
            ),
        ),
    ]
