# Generated by Django 5.2.2 on 2025-06-06 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0020_course_text_content_alter_course_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Kurs faol yoki faol emasligi",
                verbose_name="Faol",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Yangilangan sana"),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(
                help_text="Kursning to'liq nomi",
                max_length=100,
                unique=True,
                verbose_name="Kurs nomi",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="question_number",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Test savollari soni (1-100 oralig'ida)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Savollar soni",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_name"], name="exam_course_course__492730_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["created_at"], name="exam_course_created_cb8471_idx"
            ),
        ),
    ]
