# Generated by Django 5.2.2 on 2025-06-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0021_course_is_active_course_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="course",
            name="exam_course_course__492730_idx",
        ),
        migrations.RemoveIndex(
            model_name="course",
            name="exam_course_created_cb8471_idx",
        ),
        migrations.RemoveField(
            model_name="course",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="course",
            name="text_content",
        ),
        migrations.RemoveField(
            model_name="course",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(
                help_text="Kursning to'liq nomi",
                max_length=100,
                verbose_name="Kurs nomi",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Test savollarini yuklang (agar matn shaklida bo'lmasa)",
                null=True,
                upload_to="courses/questions/",
                verbose_name="Savollar rasmi",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="question_number",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maksimal test savollari soni",
                verbose_name="Savollar soni",
            ),
        ),
    ]
