# Generated by Django 5.2.2 on 2025-06-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0022_remove_course_exam_course_course__492730_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="image",
        ),
    ]
